name: iynfluencer
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.5
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  flutter_svg: ^1.1.6
  image_picker: ^1.0.1
  flutter_switch: ^0.3.2
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  flutter_screenutil: ^5.1.1
  pin_code_fields: ^7.3.0
  sms_autofill: ^2.0.0
  pin_input_text_field: 4.1.0
  intl: ^0.18.0
  http: ^0.13.0
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^8.0.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Satoshi
      fonts: 
        - asset: assets/fonts/SatoshiLight.ttf
          weight: 300
        - asset: assets/fonts/SatoshiBold.ttf
          weight: 700
        - asset: assets/fonts/SatoshiBlack.ttf
          weight: 900
    - family: Outfit
      fonts: 
        - asset: assets/fonts/OutfitRegular.ttf
          weight: 400
        - asset: assets/fonts/OutfitMedium.ttf
          weight: 500